entity_type_groups:
  node:
    event:
      basic: basic
      advanced: advanced
      facebook: facebook
      twitter_cards: twitter_cards
      schema_event: schema_event
    page:
      basic: basic
      advanced: advanced
      facebook: facebook
      twitter_cards: twitter_cards
      schema_item_list: schema_item_list
      schema_web_page: schema_web_page
    vies_application_form:
      basic: basic
      advanced: advanced
      facebook: facebook
      twitter_cards: twitter_cards
    vih_course_period:
      basic: basic
    vih_event_order:
      basic: basic
    vih_long_cource:
      basic: basic
      advanced: advanced
      facebook: facebook
      twitter_cards: twitter_cards
      schema_event: schema_event
  taxonomy_term:
    questions:
      basic: basic
    user_types:
      basic: basic
    valuation_labels:
      basic: basic
    valuation_statuses:
      basic: basic
    vih_class:
      basic: basic
      advanced: advanced
      facebook: facebook
      twitter_cards: twitter_cards
      schema_article: schema_article
      schema_web_page: schema_web_page
    vih_class_package:
      basic: basic
  user:
    user:
      basic: basic
      advanced: advanced
      facebook: facebook
      twitter_cards: twitter_cards
      schema_person: schema_person
